<?php
/**
 * @package drupal
 * @subpackage droknewsflash
 * @version 6.x-1.2 August 12, 2010
 * @author RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2010 RocketTheme, LLC
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
/*====================================
	dRokNewsFlash Module
====================================*/

/*
* Implementation of hook_block()
*/

function droknewsflash_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
	
		case 'list':
			$blocks[0]['info'] = t('dRokNewsFlash');
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
			break;
		
		// configure items on block admin page
		case 'configure':
		case 'save':
			break;
		case 'view':

            $block['subject'] = "";
			$block['content'] = theme('droknewsflash');
			return $block;
			break;
	}

}

function droknewsflash_theme() {
  return array(
    'droknewsflash' => array(
      'template' => 'droknewsflash',
      'arguments' => array('links' => array()),
    ),
  );
}

function droknewsflash_admin() {
	
	$sql = "SELECT term_node.*, term_data.* FROM term_node, term_data WHERE  term_node.tid = term_data.tid ORDER BY term_data.name";
	$result = db_query($sql);
	
	$form = array();
	
	$form['droknewsflash_rotatorCount'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Maximum number of articles to retrieve'),
	    '#default_value' => variable_get('droknewsflash_rotatorCount', 6),
	    '#size' => 4,
	    '#maxlength' => 4,
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsflash_content'] = array(
	    '#type' => 'select',
	    '#title' => t('Content to Show'),
	    '#options' => array(
			'body' => 'Body Text',
			'title' => 'Title Text'
		),
	    '#default_value' => variable_get('droknewsflash_content', 'body'),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsflash_label'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Pretext Label'),
	    '#default_value' => variable_get('droknewsflash_label', 'Updates:'),
	    '#size' => 25,
	    '#maxlength' => 25,
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsflash_category'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Category ID'),
	    '#size' => 4,
	    '#maxlength' => 2,
	    '#default_value' => variable_get('droknewsflash_category', ''),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsflash_delay'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Display Time'),
	    '#default_value' => variable_get('droknewsflash_delay', 7000),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#description' => t("Amount of time to display each news item"),
	    '#required' => TRUE,
	  );
	  
	  $form['droknewsflash_duration'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Transition Duration'),
	    '#default_value' => variable_get('droknewsflash_duration', 600),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#required' => TRUE,
	  );
	
	
	$form['droknewsflash_controls'] = array(
	    '#type' => 'select',
	    '#title' => t('Show Controls'),
	    '#options' => array(
			'true' => 'True',
			'false' => 'False'
		),
	    '#default_value' => variable_get('droknewsflash_controls', 'true'),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	
	  
	  $form['droknewsflash_preview_length'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Text Preview Length'),
	    '#default_value' => variable_get('droknewsflash_preview_length', 100),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#required' => TRUE,
	  );
	  

	
	  return system_settings_form($form);
}

function droknewsflash_menu() {

	$items = array();
	
	$items['admin/rockettheme'] = array(
		'title' => 'RocketTheme',
		'description' => 'Manage settings for custom RocketTheme Modules.',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	
	);
	
	
	$items['admin/rockettheme/droknewsflash'] = array(
	'title' => 'dRokNewsFlash ',
	'description' => 'Administer settings for dRokNewsFlash',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('droknewsflash_admin'),
	'access arguments' => array('access administration pages'),
	'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}

